<div class="paging a-right" style="line-height: 18px">
<?php if($this->getCollection()->getSize()): ?>
	<?php if($this->getLastPageNum()>1): ?>
    <?php 
		echo $this->getPagerHtml();
	?>
	<br />
	<?php endif; ?>
    <?php echo $this->__('Show') ?> <select onchange="setLocation(this.value)">
	<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
		<option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
			<?php echo $_limit ?>
		</option>
		<?php endforeach; ?>
	</select> <?php echo $this->__('per page') ?>
	<?php if( $this->isExpanded() ): ?>
	<div style="float: right; margin: 0 0 0 10px">
    <table class="view-by" cellspacing="0">
        <tr>
            <td class="sort-by">
                <?php echo $this->__('Sort by') ?> <select onchange="setLocation(this.value)">
                <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                    <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                        <?php echo $_order ?>
                    </option>
                <?php endforeach; ?>
                </select>
                <?php if($this->getCurrentDirection() == 'desc'): ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>"><img src="<?php echo $this->getSkinUrl('images/sort_desc_arrow.gif') ?>" alt="<?php echo $this->__('Set Ascending Direction') ?>" class="v-middle" /></a>
                <?php else: ?>
                    <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>"><img src="<?php echo $this->getSkinUrl('images/sort_asc_arrow.gif') ?>" alt="<?php echo $this->__('Set Descending Direction') ?>" class="v-middle" /></a>
                <?php endif; ?>
            </td>
        </tr>
    </table>
	</div>
    <?php endif; ?>
<?php endif ?>
</div>
