<?php
/**
 * Mason Web Development
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2009 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$profile = $this->getProfile();
?>
<div style="padding: 20px">
<?php if ($profile->getData("is_active")):?>
	<div class="breadcrumb" style="float: none; width: auto">
		<?php if($profile->getData("thumbnail")):?>
			<?php $marginPosition = ($profile->getThumbnailAlign() == "left") ? "float: left; margin-right: 10px;" : "float: right; margin-left: 10px;";?>
			<img src="<?php echo $profile->getThumbnailResize(100) ?>" style="<?php echo $marginPosition; ?>"/>
		<?php endif; ?>
		<h1><?php echo $profile->getData("content_heading"); ?></h1>
		<p><?php echo $this->formatDate($profile->getData("creation_time"), 'full'); ?></p>
	</div>
	<br/>&nbsp;<br/>	
	<p><?php echo $profile->getContent(); ?></p>
	<br/>
	<a href="<?php echo $this->getUrl("*/recipes/"); ?>" >&lt;&lt; back</a>
	<br/>&nbsp;
	<br/>
<?php endif;?>
</div>