<?php
	$_productCollection = $this->getLoadedProductCollection();
	if(!$_productCollection->count()) {
?>
		<div class="fclear" style="margin-bottom: 16px"></div>
<?php
		$layer = Mage::getSingleton('catalog/layer'); 
		$current_category = $layer->getCurrentCategory();
		$_categories = explode(',', $current_category->getChildren());
		if ($_imageUrl = $current_category->getImageUrl()) {
?>
			<p align="center" style="padding: 10px 0 0"><img src="<?php echo $_imageUrl?>" alt="<?php echo $current_category->getName();?>" alt="<?php echo $current_category->getName();?>" /></p>
<?php
		}
		if($current_category->getDescription() != '') {
?>
			<div><?php echo $current_category->getDescription() ?></div>
<?php
		}
		if (count($_categories)) {
?>
			<ul>
<?php
			foreach ($_categories as $_subcategory) {
				$subcat = Mage::getModel('catalog/category')->load($_subcategory);
				if($subcat->getIsActive()) {
?>
					<li>
						<b><a href="<?php echo $subcat->getUrl() ?>"><?php echo $subcat->getName() ?></a></b>
					</li>
<?php
				}
			}
?>
			</ul>
<?php
		}
	}
	else {
		echo $this->getToolbarHtml();
?>
		<div class="fclear" style="margin-bottom: 16px"></div>
<?php
		$layer = Mage::getSingleton('catalog/layer');
		$current_category = $layer->getCurrentCategory();
		$_categories = explode(',', $current_category->getChildren());
		if ($current_category->getResizedImage(541)) {
?>
			<p align="center" style="padding: 10px 0 0"><img src="<?php echo $current_category->getResizedImage(541)?>" alt="<?php echo $current_category->getName();?>" alt="<?php echo $current_category->getName();?>" /></p>
<?php
		}
		if($current_category->getDescription() != '') {
?>
			<p style="padding-left: 20px; padding-right: 20px"><?php echo $current_category->getDescription() ?></p>
<?php
		}
?>
<?php
		if (count($_categories)) {
?>
			<ul>
<?php
			foreach ($_categories as $_subcategory) {
				$subcat = Mage::getModel('catalog/category')->load($_subcategory);
				if($subcat->getIsActive()) {
?>
				<li>
					<b><a href="<?php echo $subcat->getUrl() ?>"><?php echo $subcat->getName() ?></a></b> (<?php echo $subcat->getProductCount() ?>) 
				</li>
<?php
				}
			}
?>
			</ul>
<?php
		}
		$_iterator = 0;
?>
		<div class="products">
			<table cellpadding="0" cellspacing="0">
				<tr>
<?php
		foreach ($_productCollection as $_product) {
?>
					<td>
						<div class="container">
<?php
			// Product Image
?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(154, null); ?>" width="154" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
<?php
			// Product description
?>
							<div class="description">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a>
								PRICE<br /> <b><?php echo $this->getPriceHtml($_product, true) ?></b>
                                                                <button onclick="ajaxAddToCart('<?php echo $this->getAddToCartUrl($_product) ?>')" class="form-button" title="Add to Cart" type="button"><span><span>Add to Cart</span></span></button>
							</div>
						</div>
					</td>
<?php
			$_iterator++;
			if ($_iterator == 3) {
				$_iterator = 0;
?>
				</tr>
				<tr>
					<td colspan="3" class="separator-td">&nbsp;</td>
				</tr>
				<tr>
<?php
			}
		}
?>
				</tr>
			</table>
		</div>
                <script>
                    function ajaxAddToCart(urlAddToCart) {
                        jQuery.ajax({
                            url: urlAddToCart,
                            type: 'POST',
                            success: function() {
                                // update header cart
                                var qty_add = 1;
                                var qty_old_container = jQuery('.mc-qty');
                                if (qty_old_container.length) {
                                    var qty_old = parseInt(qty_old_container.text());
                                    qty_old_container.text(qty_old + qty_add);
                                }
                                else {
                                    var insert_container = jQuery('.mini-cart');
                                    var insert_html = '<div style="padding-top: 5px"><span class="mc-qty">1</span> product in your cart</div>';
                                    insert_html += '<div class="actions"><a href="/checkout/cart/" title="Edit Cart">Edit</a> | <a href="/checkout/onepage/" title="Checkout">Checkout</a></div>';
                                    insert_container.html(insert_html);
                                }
                                // show popup
                                noty({
                                    text: 'Product added to cart. Thank You!',
                                    theme: 'default',
                                    type: 'confirm',
                                    layout: 'center',
                                    modal: true,
                                    buttons: [{
                                        addClass: 'btn btn-primary',
                                        text: 'Go to Cart',
                                        onClick: function() {
                                            window.location = '/checkout/cart/';
                                        }
                                    }, {
                                        addClass: 'btn btn-primary',
                                        text: 'Go to Checkout',
                                        onClick: function() {
                                            window.location = '/checkout/onepage/';
                                        }
                                    }, {
                                        addClass: 'btn btn-danger',
                                        text: 'Continue Shopping',
                                        onClick: function($noty) {
                                            $noty.close();
                                        }
                                    }]
                                });
                            }
                        });
                    }
                </script>
<?php
	}
?>
