<div class="fclear"></div><div class="content">
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-info-box">
    <div class="product-essential">
    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
		
		<p><?php echo $this->getChildHtml('product_type_data') ?></p>
		<p><?php echo $this->getTierPriceHtml() ?></p>
		
        <div class="product-shop">
            
            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>

            <fieldset class="no-display">
              <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
              <input type="hidden" name="related_product" id="related-products-field" value="" />
            </fieldset>

            <?php echo $this->getChildHtml('alert_urls') ?>
            
			<?php if ($this->canEmailToFriend()): ?>
                <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a>
            <?php endif; ?>
			            
            <?php if (!$this->hasOptions()):?>
                <div class="add-to-holder">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="add-or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
				<br>
            <?php else:?>
                <?php echo $this->getChildHtml('addto') ?>
            <?php endif; ?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

        </div>
        <div class="clear"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    <script type="text/javascript">
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(){
                    if (this.validator.validate()) {
                            //this.form.submit();
                            $_this = this;
                            jQuery(document).ready(function(jQuery) {
                                jQuery.ajax({
                                    url: jQuery($_this.form).attr('action'),
                                    type: 'POST',
                                    data: jQuery($_this.form).serialize(),
                                    success: function() {
                                        // update header cart
                                        var qty_add = jQuery('#qty').val();
                                        if (qty_add == '') {
                                            qty_add = 1;
                                        }
                                        var qty_old_container = jQuery('.mc-qty');
                                        if (qty_old_container.length) {
                                            var qty_old = parseInt(qty_old_container.text());
                                            qty_old_container.text(qty_old + parseInt(qty_add));
                                        }
                                        else {
                                            var insert_container = jQuery('.mini-cart');
                                            var insert_html = '';
                                            if (parseInt(qty_add) == 1) {
                                                insert_html = '<div style="padding-top: 5px"><span class="mc-qty">1</span> product in your cart</div>';
                                            }
                                            else {
                                                insert_html = '<div style="padding-top: 5px"><span class="mc-qty">' + qty_add + '</span> products in your cart</div>';
                                            }
                                            insert_html += '<div class="actions"><a href="/checkout/cart/" title="Edit Cart">Edit</a> | <a href="/checkout/onepage/" title="Checkout">Checkout</a></div>';
                                            insert_container.html(insert_html);
                                        }
                                        // show popup
                                        noty({
                                            text: 'Product added to cart. Thank You!',
                                            theme: 'default',
                                            type: 'confirm',
                                            layout: 'center',
                                            modal: true,
                                            buttons: [{
                                                addClass: 'btn btn-primary',
                                                text: 'Go to Cart',
                                                onClick: function() {
                                                    window.location = '/checkout/cart/';
                                                }
                                            }, {
                                                addClass: 'btn btn-primary',
                                                text: 'Go to Checkout',
                                                onClick: function() {
                                                    window.location = '/checkout/onepage/';
                                                }
                                            }, {
                                                addClass: 'btn btn-danger',
                                                text: 'Continue Shopping',
                                                onClick: function($noty) {
                                                    $noty.close();
                                                }
                                            }]
                                        });
                                    }
                                });
                            });
                    }
            }.bind(productAddToCartForm);
    </script>
    </div>

    <div class="product-collateral">
        <?php if ($_additional = $this->getChildHtml('additional')):?>
            <div class="collateral-box">
                <table width="100%"><tr valign="top">
				<td>
				<h4><?php echo $this->__('Additional Information') ?></h4>
                </td>
				<td><?php echo $_additional ?></td>
				</tr>
				</table>
            </div>
        <?php endif;?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
</div>