<div class="fclear"></div><div class="content">
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-info-box">
    <div class="product-essential">
    <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
		
		<p><?php echo $this->getChildHtml('product_type_data') ?></p>
		<p><?php echo $this->getTierPriceHtml() ?></p>
		
        <div class="product-shop">
            
            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>

            <fieldset class="no-display">
              <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
              <input type="hidden" name="related_product" id="related-products-field" value="" />
            </fieldset>

            <?php echo $this->getChildHtml('alert_urls') ?>
            
			<?php if ($this->canEmailToFriend()): ?>
                <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a>
            <?php endif; ?>
			            
            <?php if (!$this->hasOptions()):?>
                <div class="add-to-holder">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="add-or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
				<br>
            <?php else:?>
                <?php echo $this->getChildHtml('addto') ?>
            <?php endif; ?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

        </div>
        <div class="clear"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    <script type="text/javascript">
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(){
                    if (this.validator.validate()) {
                            this.form.submit();
                    }
            }.bind(productAddToCartForm);
    </script>
    </div>

    <div class="product-collateral">
        <?php if ($_additional = $this->getChildHtml('additional')):?>
            <div class="collateral-box">
                <table width="100%"><tr valign="top">
				<td>
				<h4><?php echo $this->__('Additional Information') ?></h4>
                </td>
				<td><?php echo $_additional ?></td>
				</tr>
				</table>
            </div>
        <?php endif;?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
</div>